services:
  stats-server:
    build: ./stats-service/stats-server
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/explore
      SPRING_DATASOURCE_USERNAME: explore_user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:15
    environment:
      POSTGRES_DB: explore
      POSTGRES_USER: explore_user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
